-- Fotos locais e estáveis para todos os exercícios do catálogo.
-- Os arquivos são versionados em public/exercises e vêm do Free Exercise DB (Unlicense).

update public.exercises
set gif_url = case
  when lower(name_pt) like 'ab wheel%' then '/exercises/Ab_Roller.jpg'
  when lower(name_pt) like 'abdominal na m%' then '/exercises/Ab_Crunch_Machine.jpg'
  when lower(name_pt) like 'agachamento b%' then '/exercises/Split_Squat_with_Dumbbells.jpg'
  when lower(name_pt) like 'agachamento no smith%' then '/exercises/Smith_Machine_Squat.jpg'
  when lower(name_pt) like 'agachamento livre%' then '/exercises/Barbell_Full_Squat.jpg'
  when lower(name_pt) like 'barra fixa assistida%' then '/exercises/Band_Assisted_Pull-Up.jpg'
  when lower(name_pt) = 'bicicleta' then '/exercises/Air_Bike.jpg'
  when lower(name_pt) = 'body saw' then '/exercises/Plank.jpg'
  when lower(name_pt) = 'cable crunch' then '/exercises/Cable_Crunch.jpg'
  when lower(name_pt) like 'cadeira extensora%' then '/exercises/Leg_Extensions.jpg'
  when lower(name_pt) like 'cadeira flexora%' then '/exercises/Lying_Leg_Curls.jpg'
  when lower(name_pt) like 'capit%' then '/exercises/Knee_Hip_Raise_On_Parallel_Bars.jpg'
  when lower(name_pt) like 'chest press%' then '/exercises/Leverage_Chest_Press.jpg'
  when lower(name_pt) like 'crossover%' then '/exercises/Cable_Crossover.jpg'
  when lower(name_pt) like 'crucifixo inclinado%' then '/exercises/Incline_Dumbbell_Flyes.jpg'
  when lower(name_pt) like 'crucifixo inverso no cabo%' then '/exercises/Cable_Rear_Delt_Fly.jpg'
  when lower(name_pt) like 'crucifixo inverso%' then '/exercises/Reverse_Machine_Flyes.jpg'
  when lower(name_pt) like 'crunch com anilha%' then '/exercises/Weighted_Crunches.jpg'
  when lower(name_pt) = 'dead bug' then '/exercises/Dead_Bug.jpg'
  when lower(name_pt) like 'desenvolvimento militar%' then '/exercises/Dumbbell_Shoulder_Press.jpg'
  when lower(name_pt) like 'desenvolvimento sentado%' then '/exercises/Machine_Shoulder_Military_Press.jpg'
  when lower(name_pt) like 'eleva%de joelhos pendurado%' then '/exercises/Hanging_Leg_Raise.jpg'
  when lower(name_pt) like 'eleva%lateral%cabo%' then '/exercises/Cable_Seated_Lateral_Raise.jpg'
  when lower(name_pt) like 'eleva%lateral%' then '/exercises/Side_Lateral_Raise.jpg'
  when lower(name_pt) like 'face pull%' then '/exercises/Face_Pull.jpg'
  when lower(name_pt) like 'flexora deitada%' then '/exercises/Lying_Leg_Curls.jpg'
  when lower(name_pt) like 'flexora sentada%' then '/exercises/Seated_Leg_Curl.jpg'
  when lower(name_pt) like 'flexora unilateral%' then '/exercises/Standing_Leg_Curl.jpg'
  when lower(name_pt) = 'hack squat' then '/exercises/Hack_Squat.jpg'
  when lower(name_pt) = 'hip thrust' then '/exercises/Barbell_Hip_Thrust.jpg'
  when lower(name_pt) = 'hollow body hold' then '/exercises/Plank.jpg'
  when lower(name_pt) = 'leg press' then '/exercises/Leg_Press.jpg'
  when lower(name_pt) = 'leg raise' then '/exercises/Flat_Bench_Lying_Leg_Raise.jpg'
  when lower(name_pt) = 'mesa flexora' then '/exercises/Lying_Leg_Curls.jpg'
  when lower(name_pt) like 'obl%quo no cabo%' then '/exercises/Standing_Cable_Wood_Chop.jpg'
  when lower(name_pt) like 'panturrilha sentada%' then '/exercises/Seated_Calf_Raise.jpg'
  when lower(name_pt) like 'panturrilha em p%' then '/exercises/Standing_Calf_Raises.jpg'
  when lower(name_pt) like 'prancha%' then '/exercises/Plank.jpg'
  when lower(name_pt) like 'pulldown pegada neutra%' then '/exercises/V-Bar_Pulldown.jpg'
  when lower(name_pt) like 'pullover%' then '/exercises/Straight-Arm_Dumbbell_Pullover.jpg'
  when lower(name_pt) like 'puxada alta%' then '/exercises/Wide-Grip_Lat_Pulldown.jpg'
  when lower(name_pt) like 'puxada unilateral%' then '/exercises/Kneeling_Single-Arm_High_Pulley_Row.jpg'
  when lower(name_pt) like 'remada com apoio no peito%' then '/exercises/Incline_Bench_Pull.jpg'
  when lower(name_pt) like 'remada curvada%' then '/exercises/Bent_Over_Barbell_Row.jpg'
  when lower(name_pt) like 'remada em m%' then '/exercises/Seated_Cable_Rows.jpg'
  when lower(name_pt) like 'remada t %' then '/exercises/T-Bar_Row_with_Handle.jpg'
  when lower(name_pt) like 'remada unilateral (serrote)%' then '/exercises/One-Arm_Dumbbell_Row.jpg'
  when lower(name_pt) like 'remada unilateral no cabo%' then '/exercises/Seated_One-arm_Cable_Pulley_Rows.jpg'
  when lower(name_pt) like 'reverse crunch%' then '/exercises/Decline_Reverse_Crunch.jpg'
  when lower(name_pt) like 'rollout com barra%' then '/exercises/Barbell_Ab_Rollout.jpg'
  when lower(name_pt) like 'rosca alternada%' then '/exercises/Alternate_Incline_Dumbbell_Curl.jpg'
  when lower(name_pt) like 'rosca direta%barra w%' then '/exercises/EZ-Bar_Curl.jpg'
  when lower(name_pt) like 'rosca direta no cabo%' then '/exercises/Standing_Biceps_Cable_Curl.jpg'
  when lower(name_pt) = 'rosca martelo' then '/exercises/Hammer_Curls.jpg'
  when lower(name_pt) like 'stiff %' or lower(name_pt) like 'terra romeno%' then '/exercises/Romanian_Deadlift.jpg'
  when lower(name_pt) = 'stomach vacuum' then '/exercises/Stomach_Vacuum.jpg'
  when lower(name_pt) like 'straight-arm pulldown%' then '/exercises/Straight-Arm_Pulldown.jpg'
  when lower(name_pt) like 'supino inclinado (barra)%' then '/exercises/Barbell_Incline_Bench_Press_-_Medium_Grip.jpg'
  when lower(name_pt) like 'supino inclinado com halteres%' then '/exercises/Incline_Dumbbell_Press.jpg'
  when lower(name_pt) like 'supino inclinado na m%' then '/exercises/Leverage_Incline_Chest_Press.jpg'
  when lower(name_pt) like 'supino reto com barra%' then '/exercises/Barbell_Bench_Press_-_Medium_Grip.jpg'
  when lower(name_pt) like 'supino reto com halteres%' then '/exercises/Dumbbell_Bench_Press.jpg'
  when lower(name_pt) like 'supino em m%' then '/exercises/Leverage_Chest_Press.jpg'
  when lower(name_pt) like '%ceps%corda%' then '/exercises/Triceps_Pushdown_-_Rope_Attachment.jpg'
  when lower(name_pt) like '%ceps%franc%' or lower(name_pt) like '%ceps%overhead%' then '/exercises/Cable_Rope_Overhead_Triceps_Extension.jpg'
  when lower(name_pt) like '%ceps%testa no cabo%' then '/exercises/Cable_Lying_Triceps_Extension.jpg'
  when lower(name_pt) like '%ceps%unilateral%' then '/exercises/Standing_Low-Pulley_One-Arm_Triceps_Extension.jpg'
  when lower(name_pt) like '%ceps%pulldown%' then '/exercises/Triceps_Pushdown_-_V-Bar_Attachment.jpg'
  when lower(name_pt) like '%ceps%testa%' then '/exercises/EZ-Bar_Skullcrusher.jpg'
  when lower(name_pt) like 'walkout%' then '/exercises/Inchworm.jpg'
  else '/exercises/Barbell_Full_Squat.jpg'
end;

alter table public.exercises
  alter column gif_url set default '/exercises/Barbell_Full_Squat.jpg';
